### ISSUE TITLE
Update senzing-entity-search-web-app with new environment variable

### ISSUE THREAD

**Issue by docktermj** [Senzing/charts#103]
**Is your feature request related to a problem? Please describe.**

1. Add support for the following environment variables in https://github.com/Senzing/charts/blob/master/charts/senzing-entity-search-web-app/senzing-entity-search-web-app/templates/deployment.yaml
   Examples:

    1. `SENZING_API_SERVER_URL`
    1. `SENZING_WEB_SERVER_ADMIN_AUTH_MODE`
    1. `SENZING_WEB_SERVER_ADMIN_AUTH_PATH`
    1. `SENZING_WEB_SERVER_PORT`
    1. Support all environment variable seen at https://github.com/Senzing/entity-search-web-app/pull/122

1. Also determine if additional default values need to be added to https://github.com/Senzing/charts/blob/4b67528b67157ed9617ab5246c401a7ded45c605/charts/senzing-entity-search-web-app/senzing-entity-search-web-app/values.yaml#L31-L33

**Comment by jeffadair** [comment]
Covered by #120
