### ISSUE TITLE
Add environment variables to senzing-stream-loader

### ISSUE THREAD

**Issue by docktermj** [Senzing/charts#105]
**Is your feature request related to a problem? Please describe.**
New environment variables have been added to https://github.com/Senzing/stream-loader/stream-loader.py

They need to be added to https://github.com/Senzing/charts/blob/4b67528b67157ed9617ab5246c401a7ded45c605/charts/senzing-stream-loader/senzing-stream-loader/templates/deployment.yaml#L19-L90

1. SENZING_CONFIG_PATH
2. SENZING_CONFIGURATION_CHECK_FREQUENCY
3. SENZING_DELAY_IN_SECONDS
4. SENZING_EXIT_ON_EMPTY_QUEUE
5. SENZING_EXIT_SLEEP_TIME_IN_SECONDS
6. SENZING_EXPIRATION_WARNING_IN_DAYS
7. SENZING_G2_CONFIGURATION_FILE
8. SENZING_INPUT_URL
9. SENZING_KAFKA_FAILURE_BOOTSTRAP_SERVER
10. SENZING_KAFKA_FAILURE_TOPIC
11. SENZING_KAFKA_INFO_BOOTSTRAP_SERVER
12. SENZING_KAFKA_INFO_TOPIC
13. SENZING_LOG_LICENSE_PERIOD_IN_SECONDS
14. SENZING_QUEUE_MAX
15. SENZING_RABBITMQ_FAILURE_EXCHANGE
16. SENZING_RABBITMQ_FAILURE_HOST
17. SENZING_RABBITMQ_FAILURE_PASSWORD
18. SENZING_RABBITMQ_FAILURE_PORT
19. SENZING_RABBITMQ_FAILURE_QUEUE
20. SENZING_RABBITMQ_FAILURE_ROUTING_KEY
21. SENZING_RABBITMQ_FAILURE_USERNAME
22. SENZING_RABBITMQ_INFO_EXCHANGE
23. SENZING_RABBITMQ_INFO_HOST
24. SENZING_RABBITMQ_INFO_PASSWORD
25. SENZING_RABBITMQ_INFO_PORT
26. SENZING_RABBITMQ_INFO_QUEUE
27. SENZING_RABBITMQ_INFO_ROUTING_KEY
28. SENZING_RABBITMQ_INFO_USERNAME
29. SENZING_RABBITMQ_PORT
30. SENZING_RABBITMQ_PREFETCH_COUNT
31. SENZING_RABBITMQ_USE_EXISTING_ENTITIES
32. SENZING_RESOURCE_PATH
33. SENZING_SKIP_DATABASE_PERFORMANCE_TEST
34. SENZING_SLEEP_TIME_IN_SECONDS
35. SENZING_SQS_FAILURE_QUEUE_URL
36. SENZING_SQS_INFO_QUEUE_URL
37. SENZING_SQS_QUEUE_URL
38. SENZING_SQS_WAIT_TIME_SECONDS
39. SENZING_SUPPORT_PATH

**Comment by jeffadair** [comment]
Already covered by #107 :
SENZING_SKIP_DATABASE_PERFORMANCE_TEST
SENZING_SQS_FAILURE_QUEUE_URL
SENZING_SQS_INFO_QUEUE_URL
SENZING_SQS_QUEUE_URL
SENZING_SQS_WAIT_TIME_SECONDS

**Comment by docktermj** [comment]
Updating helm index via https://github.com/Senzing/charts/pull/108

**Comment by docktermj** [comment]
@jeffadair Will you be packaging the Helm Chart too?  (https://github.com/Senzing/charts#package-helm-chart)

**Comment by jeffadair** [comment]
Ahh, yes, let me add that to the PR
