### ISSUE TITLE
Add environment variables to senzing-stream-producer

### ISSUE THREAD

**Issue by docktermj** [Senzing/charts#106]
**Is your feature request related to a problem? Please describe.**
New environment variables have been added to https://github.com/Senzing/stream-producer

They need to be added to https://github.com/Senzing/charts/blob/4b67528b67157ed9617ab5246c401a7ded45c605/charts/senzing-stream-producer/senzing-stream-producer/templates/job.yaml#L8-L100

1. SENZING_PASSWORD
2. SENZING_RABBITMQ_ROUTING_KEY
3. SENZING_RABBITMQ_USE_EXISTING_ENTITIES
4. SENZING_SQS_DELAY_SECONDS
5. SENZING_THREADS_PER_PRINT

See also: https://github.com/Senzing/charts/issues/105

**Comment by jeffadair** [comment]
I added some of these to stream-loader. This is for stream-producer so these are legit. Check the stream-loader python script to make sure all of the new env vars are captured.
