### ISSUE TITLE
Support for additional boto config for IAM roles

### ISSUE THREAD

**Issue by ssasidharanwp** [Senzing/charts#117]
**Is your feature request related to a problem? Please describe.**
When using IAM roles for kubernetes pods, the underlying boto library tries to get the role only once without retry and default timeout of 1 second. This is causing a problem in our current setup of huge number of pods with some of them not able to get the role and thereby the threads failing to start. This is for the stream-loader(https://github.com/Senzing/charts/tree/master/charts/senzing-stream-loader). 
This is a know issue: https://github.com/boto/botocore/issues/1617

**Describe the solution you'd like**
Can you please add support for 2 more AWS env variable for boto `AWS_METADATA_SERVICE_TIMEOUT` and `AWS_METADATA_SERVICE_NUM_ATTEMPTS` which is mentioned as a possible solution in the above boto issue link . 
Docs specifying the support for the variables: https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#credentials

These need to be added in deployment.yaml: https://github.com/Senzing/charts/blob/master/charts/senzing-stream-loader/senzing-stream-loader/templates/deployment.yaml with support to read the value of these keys from values.yaml

I tried the solution with retry set to 3 and timeout set to 10 sec and all the threads were able to get the IAM role

**Comment by docktermj** [comment]
Pull requests

1. https://github.com/Senzing/charts/pull/118

**Comment by docktermj** [comment]
@ssasidharanwp The variables have been added.  If this is sufficient, please close the issue.  If not sufficient, let us know what to improve.

**Comment by ssasidharanwp** [comment]
thank you  !! works perfectly
