### ISSUE TITLE
senzing-redoer deployment template missing awsRegion 

### ISSUE THREAD

**Issue by bdealey** [Senzing/charts#215]
**Describe the bug**
When deploying REDOER using the subcommand redo-withinfo-sqs, received error that "REGION NEEDS TO BE DEFINED" even with the region define in the helm values file:
  senzing:
    awsDefaultRegion: us-east-1

The template/deployment.yaml needs to have the following added to it (taken from the SQL Loader file

            {{- if .Values.main.senzing.awsDefaultRegion }}
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.main.senzing.awsDefaultRegion }}"
            {{- end }}

Without the template update, the helm chart will deploy, but the REDOER container will Crash with a python error stating "REGION NEEDS TO BE DEFINED".
I added this code to the template, and container was successfully deployed.

**Comment by docktermj** [comment]
@bdealey Thank you for reporting this!   I'll fix it today.

**Comment by docktermj** [comment]
@bdealey The fix has been pulled into the main branch.   If this meets your needs please close this issue.  

If we don't hear back from you in a week, (either pro or con), we'll close the issue.

Again, thanks for bringing this to our attention.

**Comment by docktermj** [comment]
No response from customer.
