### ISSUE TITLE
Pods using EmptyDir instead of correct PVC

### ISSUE THREAD

**Issue by JustinKuli** [Senzing/charts#63]
**Describe the bug**
Deploying the `senzing-package` or the `resolver` charts does not work correctly because some components are created using an EmptyDir for the volume instead of the correct PersistentVolumeClaim specified in the values.yaml.

**To Reproduce**

1. Create a persistent volume claim in the cluster (and bind it to a volume)
2. Deploy the senzing-package chart, specifying the new PVC as `optSenzingClaim` in the values.yaml
3. After the job finishes, observe that nothing has been written into the volume.

**Expected behavior**
My understanding of the chart is that things should be written into the volume.

**Additional context**
I believe `senzing-package/senzing-package/templates/job.yaml` and `resolver/resolver/templates/deployment.yaml` are the problem. Right now they have stanzas like:
```
      {{- if .Values.senzing.optSenzingClaim }}
      volumes:
        - name: opt-senzing-storage
          optSenzingClaim:
            claimName: {{ .Values.senzing.optSenzingClaim }}
      {{- end }}
```
Instead, it should be:
```
      {{- if .Values.senzing.optSenzingClaim }}
      volumes:
        - name: opt-senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.optSenzingClaim }}
      {{- end }}
```

**Comment by docktermj** [comment]
@JustinKuli Thank you!

I think this is the result of global search/replace I did a while ago.   (What a dumb idea)   I'll work on it soon.

**Comment by docktermj** [comment]
Pull Request:

1. https://github.com/Senzing/charts/pull/64

**Comment by docktermj** [comment]
@JustinKuli 

I've updated the helm charts, so please do a 
```
helm repo update
```
To get the latest.

Please let me know if this fixes the issue that you are seeing.

**Comment by JustinKuli** [comment]
I think it's working for me now! Thanks for the quick response.

**Comment by docktermj** [comment]
I'm delighted that you found the issue.  Thank you, @JustinKuli !
